Repository siderolabs/theila, pull requests merged in 2021-12, with the labels that each got.

#98 chore: define constants for all used resource types
  frontend/package-lock.json
  frontend/src/api/resources.ts
  frontend/src/context.ts
  frontend/src/views/Clusters.vue
  frontend/src/views/Servers.vue
  frontend/src/views/SidebarNode.vue
  frontend/src/views/cluster/Nodes.vue
  frontend/src/views/cluster/Pods.vue
  frontend/src/views/node/Monitor.vue
  frontend/src/views/node/Overview.vue
Labels: status/approved

#99 Add Overview and Upgrade Kubernetes Views and it's components
  .dockerignore
  .eslintrc.yaml
  .kres.yaml
  .tsconfig
  Dockerfile
  Makefile
  frontend/babel.config.js
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/THeader/THeader.vue
  frontend/src/components/common/Animation/TAnimation.vue
  frontend/src/components/common/Button/TButton.vue
  frontend/src/components/common/Dropdown/TDropdown.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/ProgressBar/TProgressBar.vue
  frontend/src/components/common/Status/TStatus.vue
  frontend/src/components/common/SystemLog/TSystemLog.vue
  frontend/src/components/common/TInput/TInput.vue
  frontend/src/components/icons/IconExternalLink.vue
  frontend/src/components/icons/IconFailAuth.vue
  frontend/src/components/icons/IconNoConnection.vue
  frontend/src/components/views/SideBar/TSideBar.vue
  frontend/src/components/views/SideBar/components/TSideBarClusterDropdown.vue
  frontend/src/components/views/SideBar/components/TSideBarClusterDropdownItem.vue
  frontend/src/components/views/SideBar/components/TSideBarClusterDropdownSubItem.vue
  frontend/src/components/views/SideBar/components/TSideBarList.vue
  frontend/src/components/views/SideBar/components/TSideBarNodesLogs.vue
  frontend/src/index.css
  frontend/src/router/index.ts
  frontend/src/views/Overview/Overview.vue
  frontend/src/views/Overview/components/TOverviewClusterStatusBox/TOverviewClusterStatusBox.vue
  frontend/src/views/Overview/components/TOverviewClusterStatusBox/TOverviewClusterStatusItem.vue
  frontend/src/views/Overview/components/TOverviewClusterStatusBox/TOverviewClusterStatusItemLog.vue
  frontend/src/views/Overview/components/TOverviewErrorView.vue
  frontend/src/views/Overview/components/TOverviewNodesUsage.vue
  frontend/src/views/Overview/components/TOverviewRightPanel/TOverviewRightPanel.vue
  frontend/src/views/Overview/components/TOverviewRightPanel/TOverviewRightPanelItem.vue
  frontend/src/views/Upgrade/Upgrade.vue
  frontend/src/views/Upgrade/components/TUpgradeHeading.vue
  frontend/src/views/Upgrade/components/TUpgradeTableBox/TUpgradeTableBox.vue
  frontend/tailwind.config.js
  frontend/tsconfig.json
  hack/dev-server.sh
  internal/frontend/frontend.go
Labels: status/ok-to-test

#100 feat: add Pods, Dashboard, Upgrade views and ect.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/THeader/THeader.vue
  frontend/src/components/THeader/THeaderTaskItem/THeaderTaskItem.vue
  frontend/src/components/common/ActionsBox/TActionsBox.vue
  frontend/src/components/common/Animation/TAnimation.vue
  frontend/src/components/common/Animation/TGroupAnimation.vue
  frontend/src/components/common/Button/TButton.vue
  frontend/src/components/common/Checkbox/TCheckbox.vue
  frontend/src/components/common/Dropdown/TDropdownNotifications.vue
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/InfoLabel/TInfoLabel.vue
  frontend/src/components/common/ProgressBar/TProgressBar.vue
  frontend/src/components/common/Shell/TShell.vue
  frontend/src/components/common/SlideDownWrapper/TSlideDownWrapper.vue
  frontend/src/components/common/Status/TStatus.vue
  frontend/src/components/common/SystemLog/TSystemLog.vue
  frontend/src/components/common/TInput/TInput.vue
  frontend/src/components/common/Watch/TWatch.vue
  frontend/src/components/icons/IconAWS.vue
  frontend/src/components/icons/IconClustersBig.vue
  frontend/src/components/icons/IconGCP.vue
  frontend/src/components/icons/IconKey.vue
  frontend/src/components/icons/IconKubeConfig.vue
  frontend/src/components/icons/IconRefresh.vue
  frontend/src/components/icons/IconSidero.vue
  frontend/src/components/icons/IconTerminal.vue
  frontend/src/components/views/SideBar/TSideBar.vue
  frontend/src/components/views/TUpgradeKubernetesModal/TUpgradeKubernetesModal.vue
  frontend/src/components/views/TUpgradeKubernetesModal/TUpgradeKubernetesSelectList.vue
  frontend/src/constants/index.ts
  frontend/src/router/index.ts
  frontend/src/views/Dashboard/TDashboard.vue
  frontend/src/views/Dashboard/components/TDashboardBottomMenu.vue
  frontend/src/views/Dashboard/components/TDashboardInstallModal.vue
  frontend/src/views/Dashboard/components/TDashboardRow.vue
  frontend/src/views/Dashboard/components/TDashboardRowItem.vue
  frontend/src/views/Overview/Overview.vue
  frontend/src/views/Overview/components/TOverviewClusterStatusBox/TOverviewClusterStatusBox.vue
  frontend/src/views/Overview/components/TOverviewClusterStatusBox/TOverviewClusterStatusItem.vue
  frontend/src/views/Overview/components/TOverviewNodesUsage.vue
  frontend/src/views/Overview/components/TOverviewRightPanel/TOverviewRightPanel.vue
  frontend/src/views/Pods/TPods.vue
  frontend/src/views/Pods/components/TPodsItem.vue
  frontend/src/views/Pods/components/TPodsList.vue
  frontend/src/views/Pods/components/TPodsSelectList.vue
  frontend/src/views/Upgrade/components/TUpgradeHeading.vue
  frontend/src/views/Upgrade/components/TUpgradeTableBox/TUpgradeTableBox.vue
  frontend/tailwind.config.js
  frontend/tsconfig.json
Labels: status/ok-to-test

#101 feat: add TPagination component
  frontend/src/components/common/Icon/TIcon.vue
  frontend/src/components/common/Pagination/TPagination.vue
  frontend/src/components/common/Status/TStatus.vue
  frontend/src/components/common/Watch/TWatch.vue
  frontend/src/components/icons/IconUnknown.vue
  frontend/src/views/Pods/TPods.vue
  frontend/src/views/Pods/components/TPodsList.vue
Labels: status/ok-to-test, status/ok-to-merge
